singleQuote: true
plugins:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-pkg
  - prettier-plugin-sh
importOrderParserPlugins:
  - typescript
  - jsx
  - decorators-legacy
  - explicitResourceManagement
