name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Node v${{matrix.node}} with graphql@${{matrix.graphql}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22, 23]
        graphql: [15, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: the-guild-org/shared-config/setup@v1
        with:
          node-version: ${{matrix.node}}
      - name: Install
        run: yarn add --dev graphql@${{matrix.graphql}}
      - name: Info
        run: yarn info graphql
      - name: Test
        run: yarn test
